# Generated by Django 4.2.7 on 2024-07-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safari_learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safaricourse',
            name='course_tags',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='safaricourse',
            name='profession_json',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='safariuser',
            name='interests',
            field=models.JSONField(null=True),
        ),
    ]
