# Generated by Django 4.2.7 on 2024-06-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safari_learning', '0002_safaricourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='safaricourse',
            name='course_name',
            field=models.CharField(default='no course name', max_length=600),
        ),
    ]
